import { SocialMediaPost, ThreatAlert, SentimentTrend } from './types';

// --- Storyline Context ---
// This mock data simulates the intelligence landscape over 72 hours leading up to the April 2024 Pahalgam attack.
// The timeline progresses from subtle chatter to a full-blown crisis, demonstrating how the system could provide early warnings.
// Day -3 (72h-48h ago): Vague chatter about "movement" in Kashmir valleys. General unease.
// Day -2 (48h-24h ago): Increased mentions of "operations" and "checkpoints". More specific locations mentioned.
// Day -1 (24h-0h ago): Spike in coded language on Telegram. News outlets begin mentioning "security concerns."
// Day 0 (Attack): The incident occurs. News and social media erupt with confirmed reports.

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000);

export const mockPosts: SocialMediaPost[] = [
  // --- Day -3: Subtle Chatter ---
  {
    id: 'p1',
    platform: 'Twitter',
    content: 'Just reached Pahalgam for a peaceful vacation. The valley is serene as ever. #Kashmir #Pahalgam',
    author: '@TouristVibes',
    timestamp: hoursAgo(72),
    location: { lat: 34.015, lng: 75.32, name: 'Pahalgam Town' },
    sentiment: 'positive',
    sentimentScore: 0.8,
    keywords: ['vacation', 'pahalgam', 'kashmir'],
    threatScore: 5,
    category: 'informational',
    isVerified: false,
    engagement: { likes: 15, shares: 2, comments: 4 },
  },
  {
    id: 'p2',
    platform: 'Reddit',
    content: 'r/kashmir - Planning a trip to Pahalgam next week. Are the roads safe? Hearing some whispers about increased movement in the region.',
    author: 'u/AnxiousTraveler',
    timestamp: hoursAgo(68),
    location: null,
    sentiment: 'neutral',
    sentimentScore: -0.2,
    keywords: ['pahalgam', 'safety', 'movement'],
    threatScore: 25,
    category: 'informational',
    isVerified: false,
    engagement: { likes: 10, shares: 1, comments: 12 },
  },
  {
    id: 'p3',
    platform: 'Twitter',
    content: 'Another day, another round of "enhanced security measures" in South Kashmir. Makes it hard for locals to move around freely.',
    author: '@KashmirLife',
    timestamp: hoursAgo(60),
    location: { lat: 33.73, lng: 75.15, name: 'Anantnag' },
    sentiment: 'negative',
    sentimentScore: -0.5,
    keywords: ['security', 'south kashmir', 'locals'],
    threatScore: 30,
    category: 'warning',
    isVerified: true,
    engagement: { likes: 88, shares: 20, comments: 15 },
  },
  
  // --- Day -2: Increased Mentions & Specificity ---
  {
    id: 'p4',
    platform: 'News',
    content: 'Security forces conduct routine patrol in Anantnag district ahead of tourist season to ensure safety and stability.',
    author: 'Kashmir Observer',
    timestamp: hoursAgo(48),
    location: { lat: 33.73, lng: 75.15, name: 'Anantnag' },
    sentiment: 'neutral',
    sentimentScore: 0.1,
    keywords: ['security', 'anantnag', 'patrol'],
    threatScore: 15,
    category: 'informational',
    isVerified: true,
    engagement: { likes: 120, shares: 45, comments: 18 },
  },
  {
    id: 'p5',
    platform: 'Telegram',
    content: 'The eagles are gathering near the river. The guests will soon receive their welcome.',
    author: 'Voice of Resistance',
    timestamp: hoursAgo(40),
    location: null,
    sentiment: 'hostile',
    sentimentScore: -0.8,
    keywords: ['eagles', 'river', 'guests'],
    threatScore: 75,
    category: 'critical',
    isVerified: false,
    engagement: { likes: 0, shares: 0, comments: 0 },
  },
  {
    id: 'p6',
    platform: 'Twitter',
    content: 'Multiple checkpoints set up on the Anantnag-Pahalgam road. Causing massive traffic jams. What\'s going on? #Kashmir #Checkpoint',
    author: '@PahalgamResident',
    timestamp: hoursAgo(36),
    location: { lat: 33.85, lng: 75.25, name: 'Anantnag-Pahalgam Road' },
    sentiment: 'negative',
    sentimentScore: -0.6,
    keywords: ['checkpoint', 'anantnag', 'pahalgam', 'traffic'],
    threatScore: 55,
    category: 'warning',
    isVerified: false,
    engagement: { likes: 45, shares: 15, comments: 22 },
  },
  
  // --- Day -1: Spike in Coded Language & Warnings ---
   {
    id: 'p7',
    platform: 'Reddit',
    content: 'r/kashmir - Seeing a lot of strange movement near Pahalgam. Anyone else notice this? Seems like more than just tourists.',
    author: 'u/ValleyWatcher',
    timestamp: hoursAgo(22),
    location: { lat: 34.02, lng: 75.33, name: 'Near Pahalgam' },
    sentiment: 'negative',
    sentimentScore: -0.6,
    keywords: ['movement', 'pahalgam', 'suspicious'],
    threatScore: 60,
    category: 'warning',
    isVerified: false,
    engagement: { likes: 32, shares: 5, comments: 25 },
  },
  {
    id: 'p8',
    platform: 'Telegram',
    content: 'Warning to outsiders in the valley. Your presence is not welcome. The resistance continues.',
    author: 'Unknown Channel',
    timestamp: hoursAgo(18),
    location: null,
    sentiment: 'hostile',
    sentimentScore: -0.9,
    keywords: ['warning', 'outsiders', 'resistance'],
    threatScore: 85,
    category: 'critical',
    isVerified: false,
    engagement: { likes: 0, shares: 0, comments: 0 },
  },
  {
    id: 'p9',
    platform: 'News',
    content: 'Intelligence agencies have issued a high alert for the Kashmir valley, citing credible inputs of a possible terror attack on tourist locations.',
    author: 'India Today',
    timestamp: hoursAgo(12),
    location: { lat: 34.08, lng: 74.79, name: 'Srinagar' },
    sentiment: 'negative',
    sentimentScore: -0.8,
    keywords: ['alert', 'kashmir', 'terror attack', 'tourist'],
    threatScore: 90,
    category: 'critical',
    isVerified: true,
    engagement: { likes: 800, shares: 350, comments: 120 },
  },
  {
    id: 'p10',
    platform: 'Twitter',
    content: 'The atmosphere in Pahalgam is very tense. Heavy security deployment everywhere. Not the vacation we were hoping for.',
    author: '@DisappointedTourist',
    timestamp: hoursAgo(8),
    location: { lat: 34.01, lng: 75.31, name: 'Pahalgam' },
    sentiment: 'negative',
    sentimentScore: -0.7,
    keywords: ['pahalgam', 'tense', 'security'],
    threatScore: 65,
    category: 'warning',
    isVerified: false,
    engagement: { likes: 25, shares: 8, comments: 14 },
  },

  // --- Day 0: The Attack ---
  {
    id: 'p11',
    platform: 'Twitter',
    content: 'Loud bangs heard near main market in Pahalgam! Everyone is running! What is happening?!',
    author: '@ScaredLocal',
    timestamp: hoursAgo(1.5),
    location: { lat: 34.013, lng: 75.318, name: 'Pahalgam Market' },
    sentiment: 'hostile',
    sentimentScore: -0.95,
    keywords: ['bangs', 'pahalgam', 'running'],
    threatScore: 98,
    category: 'critical',
    isVerified: false,
    engagement: { likes: 150, shares: 90, comments: 40 },
  },
  {
    id: 'p12',
    platform: 'Twitter',
    content: 'Reports of an incident near Pahalgam. Heavy security presence. Details are still emerging. Praying for everyone\'s safety.',
    author: '@KashmirIntel',
    timestamp: hoursAgo(1),
    location: { lat: 34.01, lng: 75.31, name: 'Pahalgam' },
    sentiment: 'negative',
    sentimentScore: -0.8,
    keywords: ['incident', 'pahalgam', 'security'],
    threatScore: 95,
    category: 'critical',
    isVerified: true,
    engagement: { likes: 540, shares: 210, comments: 80 },
  },
    {
    id: 'p13',
    platform: 'News',
    content: 'BREAKING: Terrorist attack on a tourist vehicle confirmed in Pahalgam. Casualties reported. Security forces have cordoned off the area.',
    author: 'Greater Kashmir',
    timestamp: hoursAgo(0.5),
    location: { lat: 34.012, lng: 75.315, name: 'Pahalgam Attack Site' },
    sentiment: 'hostile',
    sentimentScore: -1.0,
    keywords: ['attack', 'terrorist', 'pahalgam', 'casualties'],
    threatScore: 100,
    category: 'critical',
    isVerified: true,
    engagement: { likes: 2500, shares: 1200, comments: 450 },
  },
  // Adding more posts to reach 30-40
    {
    id: 'p14',
    platform: 'Telegram',
    content: 'The package is ready for delivery. The address is the valley of shepherds. Timing is critical.',
    author: 'Handler77',
    timestamp: hoursAgo(28),
    location: null,
    sentiment: 'hostile',
    sentimentScore: -0.85,
    keywords: ['package', 'delivery', 'shepherds', 'timing'],
    threatScore: 88,
    category: 'critical',
    isVerified: false,
    engagement: { likes: 0, shares: 0, comments: 0 },
  },
    {
    id: 'p15',
    platform: 'Reddit',
    content: 'r/geopolitics - Discussion thread: Rising tensions in J&K ahead of summer tourist season. What are the indicators to watch?',
    author: 'u/GeopoliticsMod',
    timestamp: hoursAgo(55),
    location: null,
    sentiment: 'neutral',
    sentimentScore: -0.1,
    keywords: ['j&k', 'geopolitics', 'tensions'],
    threatScore: 20,
    category: 'informational',
    isVerified: false,
    engagement: { likes: 150, shares: 30, comments: 95 },
  },
    {
    id: 'p16',
    platform: 'Twitter',
    content: 'Helicopters seen flying low over Pahalgam this morning. Seems like a security drill.',
    author: '@AviationGeek',
    timestamp: hoursAgo(10),
    location: { lat: 34.02, lng: 75.32, name: 'Pahalgam' },
    sentiment: 'neutral',
    sentimentScore: 0.0,
    keywords: ['helicopters', 'pahalgam', 'security'],
    threatScore: 40,
    category: 'informational',
    isVerified: false,
    engagement: { likes: 18, shares: 3, comments: 7 },
  },
   {
    id: 'p17',
    platform: 'News',
    content: 'Home Ministry advises tourists in Kashmir to remain vigilant and cooperate with security forces amid heightened threat perception.',
    author: 'ANI',
    timestamp: hoursAgo(15),
    location: { lat: 28.61, lng: 77.23, name: 'New Delhi' },
    sentiment: 'negative',
    sentimentScore: -0.7,
    keywords: ['tourists', 'kashmir', 'vigilant', 'threat'],
    threatScore: 80,
    category: 'warning',
    isVerified: true,
    engagement: { likes: 600, shares: 250, comments: 90 },
  },
];


export const mockAlerts: ThreatAlert[] = [
    {
        id: 'a1',
        title: 'Unusual Telegram Activity',
        description: 'Coded messages discussing "guests" and "eagles" detected, potentially referring to targets and operatives.',
        location: { lat: 33.9, lng: 75.2, name: 'South Kashmir Region' },
        threatLevel: 'medium',
        threatScore: 78,
        relatedPosts: ['p5', 'p14'],
        detectedAt: hoursAgo(27),
        status: 'monitoring',
        category: 'Coded Communication',
    },
    {
        id: 'a2',
        title: 'Reports of Checkpoint Concerns',
        description: 'Multiple civilian posts report an unusual number of security checkpoints on the Anantnag-Pahalgam route, indicating a potential security operation or threat.',
        location: { lat: 33.85, lng: 75.25, name: 'Anantnag-Pahalgam Road' },
        threatLevel: 'high',
        threatScore: 65,
        relatedPosts: ['p3', 'p6'],
        detectedAt: hoursAgo(35),
        status: 'active',
        category: 'Security Posture Change',
    },
    {
        id: 'a3',
        title: 'Coordinated Hostile Chatter',
        description: 'A sharp increase in hostile posts and direct warnings targeting "outsiders" in the Pahalgam area has been detected across multiple platforms.',
        location: { lat: 34.015, lng: 75.32, name: 'Pahalgam' },
        threatLevel: 'high',
        threatScore: 88,
        relatedPosts: ['p8', 'p5', 'p7'],
        detectedAt: hoursAgo(16),
        status: 'active',
        category: 'Pre-Attack Coordination',
    },
     {
        id: 'a4',
        title: 'Official High Alert Issued',
        description: 'Verified news sources and government agencies have issued a high alert for tourist locations in Kashmir, corroborating intelligence from social media.',
        location: { lat: 34.08, lng: 74.79, name: 'Kashmir Valley' },
        threatLevel: 'critical',
        threatScore: 92,
        relatedPosts: ['p9', 'p17'],
        detectedAt: hoursAgo(11),
        status: 'active',
        category: 'Official Warning',
    },
    {
        id: 'a5',
        title: 'Pahalgam Attack Confirmed',
        description: 'Multiple verified news and social media reports confirm an active terrorist incident in Pahalgam, with reports of casualties.',
        location: { lat: 34.012, lng: 75.315, name: 'Pahalgam Attack Site' },
        threatLevel: 'critical',
        threatScore: 100,
        relatedPosts: ['p11', 'p12', 'p13'],
        detectedAt: hoursAgo(1),
        status: 'active',
        category: 'Active Incident',
    }
];

export const mockSentimentTrends: SentimentTrend[] = [
    { timestamp: hoursAgo(72), positiveCount: 12, neutralCount: 18, negativeCount: 3, hostileCount: 0, totalPosts: 33 },
    { timestamp: hoursAgo(60), positiveCount: 10, neutralCount: 20, negativeCount: 8, hostileCount: 1, totalPosts: 39 },
    { timestamp: hoursAgo(48), positiveCount: 8, neutralCount: 25, negativeCount: 12, hostileCount: 2, totalPosts: 47 },
    { timestamp: hoursAgo(36), positiveCount: 6, neutralCount: 22, negativeCount: 18, hostileCount: 6, totalPosts: 52 },
    { timestamp: hoursAgo(24), positiveCount: 4, neutralCount: 18, negativeCount: 25, hostileCount: 12, totalPosts: 59 },
    { timestamp: hoursAgo(12), positiveCount: 2, neutralCount: 10, negativeCount: 35, hostileCount: 20, totalPosts: 67 },
    { timestamp: hoursAgo(1), positiveCount: 1, neutralCount: 5, negativeCount: 40, hostileCount: 35, totalPosts: 81 },
];
